import { Navbar } from '../components/Navbar';

export function Terms() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />
      <main className="max-w-3xl mx-auto px-6 py-12 prose prose-gray">
        <h1>Terms of Service</h1>
        <p className="text-sm text-gray-500">Last updated: 1 May 2026</p>

        <p>
          By creating an account or using EduVidQA, you agree to these terms. If you do not
          agree, do not use the service.
        </p>

        <h2>1. Acceptable Use</h2>
        <ul>
          <li>EduVidQA is for personal, educational use.</li>
          <li>
            Do not abuse the LLM endpoints (e.g. automated bulk requests, prompt-injection
            attacks, attempts to extract system prompts or private user data).
          </li>
          <li>Do not scrape, mirror, or redistribute the service or its outputs at scale.</li>
          <li>Do not use the service to generate harmful, illegal, or harassing content.</li>
        </ul>

        <h2>2. YouTube Content</h2>
        <p>
          Videos shown in EduVidQA are embedded via the YouTube IFrame Player API. We do not
          host, modify, or own these videos. All copyrights remain with their respective
          owners. Your use of embedded video content is also governed by{' '}
          <a href="https://www.youtube.com/t/terms" target="_blank" rel="noreferrer">
            YouTube's Terms of Service
          </a>
          .
        </p>

        <h2>3. AI-Generated Content Disclaimer</h2>
        <p>
          <strong>
            Answers, quiz questions, and explanations are generated by large language models
            and may contain errors, omissions, or hallucinations.
          </strong>{' '}
          Always verify important information against the original lecture and primary
          sources. EduVidQA is a study aid, not a substitute for the lecture itself or for
          professional advice.
        </p>

        <h2>4. Account Termination</h2>
        <p>
          We may suspend or terminate accounts that violate these terms, abuse our
          infrastructure, or attempt to circumvent rate limits. You may delete your account at
          any time from the app or by emailing us.
        </p>

        <h2>5. Limitation of Liability</h2>
        <p>
          The service is provided <strong>"as is"</strong>, without warranties of any kind. To
          the maximum extent permitted by law, we are not liable for any indirect, incidental,
          or consequential damages arising from your use of the service, including reliance on
          AI-generated answers.
        </p>

        <h2>6. Changes to These Terms</h2>
        <p>
          We may update these terms from time to time. Material changes will be announced in
          the app. Continued use of the service after changes take effect constitutes
          acceptance of the new terms.
        </p>

        <h2>7. Contact</h2>
        <p>
          Questions: <a href="mailto:legal@eduvidqa.app">legal@eduvidqa.app</a>
        </p>
      </main>
    </div>
  );
}
